const DataAdapter = [{"id":1,"city":"Vol’no-Nadezhdinskoye","from":"4/11/2022","to":"8/21/2021","desc":"Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.","country":"Russia","image":"http://dummyimage.com/200x100.png/dddddd/000000"},
{"id":2,"city":"Maungatapere","from":"4/18/2022","to":"3/30/2022","desc":"Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.","country":"New Zealand","image":"http://dummyimage.com/200x100.png/dddddd/000000"},
{"id":3,"city":"Cuauhtemoc","from":"11/2/2021","to":"3/17/2022","desc":"Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.","country":"Mexico","image":"http://dummyimage.com/200x100.png/5fa2dd/ffffff"},
{"id":4,"city":"Strasbourg","from":"8/17/2021","to":"12/8/2021","desc":"Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.","country":"France","image":"http://dummyimage.com/200x100.png/ff4444/ffffff"},
{"id":5,"city":"Datagon","from":"12/15/2021","to":"11/15/2021","desc":"Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.","country":"Philippines","image":"http://dummyimage.com/200x100.png/cc0000/ffffff"},
{"id":6,"city":"Ferbane","from":"1/9/2022","to":"3/3/2022","desc":"Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.","country":"Ireland","image":"http://dummyimage.com/200x100.png/ff4444/ffffff"},
{"id":7,"city":"Calingcuan","from":"1/18/2022","to":"1/7/2022","desc":"Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.","country":"Philippines","image":"http://dummyimage.com/200x100.png/5fa2dd/ffffff"},
{"id":8,"city":"Santa Cecília","from":"3/15/2022","to":"1/29/2022","desc":"Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.","country":"Brazil","image":"http://dummyimage.com/200x100.png/cc0000/ffffff"},
{"id":9,"city":"Pilar do Sul","from":"7/31/2021","to":"12/21/2021","desc":"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.","country":"Brazil","image":"http://dummyimage.com/200x100.png/cc0000/ffffff"},
{"id":10,"city":"Jiebu","from":"4/5/2022","to":"11/15/2021","desc":"Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.","country":"China","image":"http://dummyimage.com/200x100.png/cc0000/ffffff"},
{"id":11,"city":"Agoncillo","from":"12/22/2021","to":"3/10/2022","desc":"Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.","country":"Philippines","image":"http://dummyimage.com/200x100.png/ff4444/ffffff"},
{"id":12,"city":"Cordova","from":"1/30/2022","to":"9/17/2021","desc":"Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.","country":"Philippines","image":"http://dummyimage.com/200x100.png/dddddd/000000"},
{"id":13,"city":"Tubualá","from":"5/22/2022","to":"6/7/2022","desc":"Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.","country":"Panama","image":"http://dummyimage.com/200x100.png/5fa2dd/ffffff"},
{"id":14,"city":"Öndörhoshuu","from":"10/25/2021","to":"3/31/2022","desc":"Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.","country":"Mongolia","image":"http://dummyimage.com/200x100.png/5fa2dd/ffffff"},
{"id":15,"city":"Ōkawa","from":"1/19/2022","to":"11/10/2021","desc":"Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum.","country":"Japan","image":"http://dummyimage.com/200x100.png/ff4444/ffffff"}]

export default DataAdapter